################################################################################
# This file defines exactly how we will validate your models. Please carefully
# look through what is present here and make sure you understand what each
# function does.
#
# NOTE: If your submitted code fails any of the requirements in this file, we
# will have to contact you to resubmit. If there is no time, then you will be
# automatically disqualified. So please make sure this code file runs perfectly
# and read the outputs before submitting.
################################################################################


# LOAD THE NECESSARY PACKAGES HERE ---------------------------------------------

# DO NOT ALTER BEYOND THIS POINT -----------------------------------------------
load("code.R")  # Loading the function definitions your code.R

profit_checker = function(data_year1, data_year2, trained_model){

    # (DO NOT ALTER THIS FUNCTION)
    #
    # This function checks whether your model makes money on both years of the
    # training data.
    #
    # Inputs:
    #    - data_year1: A dataframe. This is the training data for year 1
    #    - data_year2: A dataframe. This is the training data for year 2
    #    - trained_model: This is the result of your train() function that was
    #                    saved as 'trained_model.RData'
    #
    #  Outputs:
    #    - makes_profit: A boolean (True or False). Indicates whether your model
    #                    makes a profit on training data from both year 1 and
    #                    year 2
     
    year1_loss = sum(data_year1[,'AMOUNT'])
    year2_loss = sum(data_year2[,'AMOUNT'])

    year1_revenue = sum(apply(data_year1, 1, predict_premium, trained_model))
    year2_revenue = sum(apply(data_year2, 1, predict_premium, trained_model))
    
    year1_profit = year1_revenue - year1_loss
    year2_profit = year2_revenue - year2_loss

    makes_profit = (year1_profit > 0) & (year2_profit > 0)
    return(makes_profit)
}

validate_model = function(trained_model, fake_year3){
     
    # (DO NOT ALTER THIS FUNCTION)
    #
    # This function ensures that your predict function does indeed create the
    # validation_year3.csv file that was created by using your saved model.
    #
    # Inputs:
    #    - trained_model: This is the result of the train() function
    #    - fake_year3: A dataframe containing randomly generated fake data
    #                  
    #
    # Outputs:
    #    - match: A boolean value (True or False) indicating whether the
    #             validation_year3 file matches what is created by your
    #             predict_premium in code.R
  
    
    # Loading the validation_year3.csv file generated by code.R
    val_year3 = read.csv('validation_year3.csv')
    
    submitted_premiums = val_year3['PREMIUM']  # These are your prices
  
    
    # Making row-wise predictions on the fake_year3.csv
    live_premiums = apply(fake_year3, 1, predict_premium, trained_model)

    match = abs(submitted_premiums - live_premiums) < 1e-10
    match = prod(match) == 1
    return(match)
}

model_checker = function(){
    
    # (DO NOT ALTER THIS FUNCTION)
    #
    # This function checks that your model is valid by running the
    # validate_model() function.
    #
    # It then checks whether your model is profitable on training data.
    #
    # If either of the above two fails it will raise an assertion error. 

    cat('Loading the data ------------------------------------------- \n')
    data_year1 = read.csv('data_year1.csv')
    data_year2 = read.csv('data_year2.csv')
    fake_year3 = read.csv('fake_year3.csv')
    
    cat('Loading your model ----------------------------------------- \n')
    
    load(file = 'trained_model.RData')
    
    cat('\nIs your model valid on fake data?             ')
    valid = validate_model(trained_model, fake_year3)
    cat(valid)

    cat('\nDoes your model make money on training data?  ')
    profit = profit_checker(data_year1, data_year2, trained_model)
    cat(profit)

    cat('\nCan you upload your model as is?              ')
    cat(profit & valid)
    cat('\n\n')
}


# Finally the model_checker() is executed
model_checker()
